version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clines
    ports:
      - "5432:5432"
    volumes:
    - db-volume:/var/lib/postgresql/data
  api:
    image: caelum/clines-api
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      DB_HOST: database
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

volumes:
  db-volume:
